# Copyright 2017 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readvertiser
  namespace: default
  labels:
    app: readvertiser
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: readvertiser
  labels:
    app: readvertiser
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  resourceNames:
  - kube-apiserver
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: readvertiser
  name: readvertiser
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: readvertiser
subjects:
- kind: ServiceAccount
  name: readvertiser
  namespace: default
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: readvertiser
  namespace: default
  labels:
    app: readvertiser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readvertiser
  template:
    metadata:
      labels:
        app: readvertiser
    spec:
      serviceAccountName: readvertiser
      tolerations:
      - effect: NoExecute
        operator: Exists
      containers:
      - name: readvertiser
        image: eu.gcr.io/sap-cloud-platform-dev1/garden/aws-lb-readvertiser:v0.0.2
        imagePullPolicy: IfNotPresent
        args:
        - "--name=kube-apiserver"
        - "--elb=api.example.com"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
