[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

# https://github.com/kubernetes/apimachinery/issues/46
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true